# Generated by Django 4.2.2 on 2023-06-22 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('34c9c8d7-d7b7-42d8-b1ca-c0a05dad9a76'), editable=False, primary_key=True, serialize=False),
        ),
    ]
